### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ekrogh**
Legend formatting on iOS and Android should now be as original.

Changes made previous

- LabelTextSize is now bindable

- Added new bindable property, LegendItemSpacing

- Added .GTK project and screen dumps of gtk windows.

- Changes to make Legend show on macOS, UWP and GTK platforms

- Label text formatting.

Best
Eigil

### CODE REVIEW

**Comment by NdubuisiJr** [comment]
Hi Eigil

Thanks for the pull request.
I will promptly review the changes as soon as possible.

Kind Regards

**Comment by ekrogh** [comment]
Hi Ndubuisi Jr,

 

Maybe you should a little. I ran TestApp on my iPhone and it did not look as good as desired. I think I will try to merge your solution for legend back, and use it for Android and iOS.

 

Kind regards

Eigil

**Comment by ekrogh** [comment]
Hi Ndubuisi Jr,

 

Maybe you should hesitate a little. I ran TestApp on my iPhone and it did not look as good as desired. I think I will try to merge your solution for legend back, and use it for Android and iOS.

 

Kind regards

Eigil

**Comment by NdubuisiJr** [comment]
HI Eigil

I was going to bring that to your notice.
I was looking at away of managing both your legend implementation and mine.
I spent a lot of time on it yesterday but just haven't found a suiting combination yet.

Try what you can about it and update the PR accordingly. I want to focus on adding some new Chart Types into the library.

Kind Regards

**Comment by ekrogh** [comment]
Hi Ndubuisi,

 

Legend formatting on iOS and Android should now be as original.

 

Changes made previous

 

·         LabelTextSize is now bindable

 

·         Added new bindable property, LegendItemSpacing

 

·         Added .GTK project and screen dumps of gtk windows.

 

·         Changes to make Legend show on macOS, UWP and GTK platforms

 

·         Label text formatting.

 

Kind regards

Eigil

**Comment by NdubuisiJr** [comment]
Awesome...

I'll take a look and follow-through.

Thanks and Kind Regards

**Comment by NdubuisiJr** [comment]
Hi Eigil
The X and Y labels do not fit properly around the tick labels. Then tend to overlap when the number of digits in the tick increases.
So, I'm considering rendering the X-Y labels on the opposite side of the tick labels.
What do you think?

**Comment by ekrogh** [comment]
Hi Ndubuisi,

 

That is OK!

 

Eigil

**Comment by ekrogh** [comment]
Why Does a Thumbs-Up Gesture Mean “okay”? | guernseydonkey.com

 

Thumbs up!

 

Tested the development branch from https://github.com/NdubuisiJr/skia-chart.git  on all platforms (Android and iOS on simulators).

 

It looks great!

 

Kind regards

**Comment by NdubuisiJr** [comment]
Hi Eigil

Thanks for your contributions so far. It has been an awesome experience working with you...
Still, feel free to play around with the code to see what we can improve. 
I'm working on another chart type. Once it's ready, I'll release a new version of the plugin.

Thanks and Kind Regards.

**Comment by ekrogh** [comment]
Hi Ndubuisi,

I could use a plot with Date/Time x-axis. Will try to look into that.

Kind regards
 Eigil

**Comment by NdubuisiJr** [comment]
Hi Eigil

Currently one can plot Date/Time values by converting it to strings. That's how I thought of it.
I will be very excited to see what you come up with.

Thanks and Kind Regards

**Comment by ekrogh** [comment]
Ndubuisi,

 

Yes I realized that just after I sent the e-mail.

 

The x-axes labels as strings works fine for me, so I won’t make any changes for Date/time.

 

 

Kind regards,

Eigil

**Pull request merged**
